### ISSUE TITLE
Where is the CHANGELOG for plugin-SecurityInfo

### ISSUE THREAD

**Issue by ZerooCool** [matomo-org/plugin-SecurityInfo#33]
# New version - Verify the changelog
# https://github.com/ZerooCool/phpsecinfo

PhpSecInfo fournit un équivalent de la fonction phpinfo () qui rapporte des informations de sécurité sur l'environnement PHP et offre des suggestions d'amélioration.
Il ne remplace pas les techniques de développement sécurisées et ne fait aucun type d'audit de code ou d'application, mais peut constituer un outil utile dans une approche de sécurité multicouche.

Le site officiel de 2012 pour PhpSecInfo : http://phpsec.org/projects/phpsecinfo/index.html

Le lien officiel pour télécharger la version de PhpSecInfo de 2007 v0.2.1 : http://phpsec.org/projects/phpsecinfo/phpsecinfo.zip
Le lien officiel pour télécharger la version de PhpSecInfo de 2009 v0.2.2 : https://github.com/funkatron/phpsecinfo

Ce travail de mise à jour n'a pas pris en compte les précédentes mises à jour de 2009.
Le lien non officiel pour télécharger la version de PhpSecInfo de 2009 v2.0.1a -> v2.0.2 de 2016 : https://github.com/bigdeej/PhpSecInfo

Un fork de PhpSecInfo vers SecurityInfo.
Le CHANGELOG n'est pas présent pour suivre l'évolution du projet.
Ce travail de mise à jour n'a pas du prendre en compte les précédentes mises à jour de la v2.2 ou de la v2.0.1a -> v2.0.2 de 2016.
Le lien officiel pour télécharger la version de SecurityInfo basé notamment sur PhpSecInfo de 2009 : https://github.com/matomo-org/plugin-SecurityInfo

----------------------------------

https://github.com/funkatron/phpsecinfo/blob/master/CHANGELOG
https://github.com/bigdeej/PhpSecInfo/blob/master/CHANGELOG

**Comment by tsteur** [comment]
@ZerooCool not sure I understand the issue and what it is about?
We don't really have any changelog for this plugin. The only changelog be the commits itself: https://github.com/matomo-org/plugin-SecurityInfo/commits/master and the information in the releases: https://github.com/matomo-org/plugin-SecurityInfo/releases

Does this help?

**Comment by ZerooCool** [comment]
Hello, to be clearer, I saw that you integrate PhpSecInfo but I do not know which version you have integrated.

I saw that there are two official versions:
- PhpSecInfo de 2007 v0.2.1 : http://phpsec.org/projects/phpsecinfo/phpsecinfo.zip
- PhpSecInfo de 2009 v0.2.2 : https://github.com/funkatron/phpsecinfo - https://github.com/funkatron/phpsecinfo/blob/master/CHANGELOG

I have not found the CHANGELOG of PhpSecInfo and therefore I do not know what your integration is based on.

By cons, I saw that you have made patches, so I added you in the list of four PhpSecInfo projects that I could identify.

It would be interesting to rely on the 2009 v0.2.2 release to include the patches identified on the PhpSecInfo version of 2009 v2.0.1a -> v2.0.2 de 2016 : https://github.com/bigdeej/PhpSecInfo

**Comment by tsteur** [comment]
See here: it is 0.2.2 https://github.com/matomo-org/plugin-SecurityInfo/blob/master/PhpSecInfo/PhpSecInfo.php#L20

**Comment by ZerooCool** [comment]
Ok. Thank you.
