### ISSUE TITLE
Add .gitattributes for a repo Windows <-> Linux compatible

### ISSUE THREAD

**Issue by ZerooCool** [matomo-org/plugin-SecurityInfo#34]
This .gitattributes :
https://gitattributes.io/api/web

For your .gitignore, you can add .gitignore in the .gitignore file, no ?

**Comment by tsteur** [comment]
Hi there, I don't think this is needed for us. Cheers

**Comment by ZerooCool** [comment]
Are you sure ?
If the code is open, it is to allow reuse, and, improvement?
I was able to see your changes on the file:
https://github.com/matomo-org/plugin-SecurityInfo/commits/master/PhpSecInfo/Test/Core/upload_tmp_dir.php

There are precisely modifications on the end of line.
This is proof that at one point there were problems with the end of the file line.

If I am not mistaken, the initial project of 2007 was created on Windows which added the end of line CRLF.

On your deposit, you have lost the end of the line CRLF which forced you to the remettres.

I had the same problem on my recovered repository based on the 2007 version. I am running Linux.

By adding the .gitattributes file as proposed, Windows and Linux users could use the same repository without encountering any difficulties.
On the other hand, the end of line on the deposit should be ironed in LF. Using the Php-codeSniffer script from a Linux terminal to format all project files to the PSR-2 standard should remove the end-of-line windows.

From there, the .gitattributes file makes the project compatible, without any other necessary configuration, if I am not mistaken.

Another example: I am integrating the proposed patches on version 2.0.2 that you have not taken into account. This is an alternative deposit dated 2016. https://github.com/bigdeej/PhpSecInfo

Therefore, if I correct on my side, while including your own modifications, I can not propose to you of Pull request, because our ends of lines will be different, which will force a treatment of the end of line, out, that can be avoided with the .gitattributes file

Can you clarify, when you say you do not need it?
If you do otherwise, can you specify?

**Comment by tsteur** [comment]
The https://gitattributes.io/api/web had so many entries for files we don't have which why I thought it shouldn't be needed. We could potentially merge it for php files etc. Maybe create a PR for it?

**Comment by ZerooCool** [comment]
Indeed, the proposed .gitattributes is a complete version for a web project, which seems so consistent, and to use, even if we do not meet the need of all its options.

Yes for the PR but, I do not know if we can then manage the end of line.

In any case, after all my readings, I think I understood that a good Git repository must have LF line endings, and it's up to everyone (under windows or linux but under linux is already the case) to make sure to push to the filing of files in LF.

It is a good practice to encourage, to facilitate the collaboration between Windows Linux Mac.

That's why I'm going back to this learning because to date, you use the latest version of PhpSecInfo.

My synthesis:
https://github.com/ZerooCool/phpsecinfo/wiki/Configurer-le-d%C3%A9p%C3%B4t-pour-la-collaboration-Unix-et-Windows
