### ISSUE TITLE
Adapt the message for upload_tmp_dir

### ISSUE THREAD

**Issue by ZerooCool** [matomo-org/plugin-SecurityInfo#35]
Thank you, this test also works in my case.

https://github.com/matomo-org/plugin-SecurityInfo/commit/28c87c0dcbe76e025e6c250f10aea48203c0c421#diff-af85a9dee2b2562f601a8f87c7f345d7

```
&& !preg_match("%^" . PHPSECINFO_TEST_COMMON_TMPDIR . "(/|$)%", $this->current_value)
            && !($perms & 0x0004)
            && !($perms & 0x0002)
```

```
**Pass**
upload_tmp_dir is enabled, which is the recommended setting. 
Make sure your upload_tmp_dir path is not world-readable

Current Value: | /var/www/folder_tmp_php
Recommended Value: | A non-world readable/writable directory
```

It would be good to adapt the message, because if the test is passed, it is good that the file is non-world readable, right?

I have chmod 750 my folder folder_tmp_php which belongs to www-data: www-data in the folder /var/www/

As a result, the message seems inappropriate.

**Comment by tsteur** [comment]
Wouldn't you need to change that test in the PhpSecInfo library?

**Comment by ZerooCool** [comment]
What do you mean by changing the text in the PhpSecInfo library?
Can you explain ?

In upload_tmp_dir.php

Change :
```
        $this->setMessageForResult(PHPSECINFO_TEST_RESULT_OK, 'en', 'upload_tmp_dir is enabled, which is the recommended setting. Make sure your upload_tmp_dir path is not world-readable');
```

by :
`        $this->setMessageForResult(PHPSECINFO_TEST_RESULT_OK, 'en', 'upload_tmp_dir is enabled, which is the recommended setting.');`

**Comment by tsteur** [comment]
I suppose you would want to suggest these changes here: https://github.com/funkatron/phpsecinfo

**Comment by ZerooCool** [comment]
No, for your code too :
https://github.com/matomo-org/plugin-SecurityInfo/blob/master/PhpSecInfo/Test/Core/upload_tmp_dir.php

line 95 / 96

```
        $this->setMessageForResult(PHPSECINFO_TEST_RESULT_OK, 'en', 'upload_tmp_dir is enabled, which is the
						recommended setting. Make sure your upload_tmp_dir path is not world-readable');
```
The message is wrong. If the test is OK, all steep was checked, then use only : 

`$this->setMessageForResult(PHPSECINFO_TEST_RESULT_OK, 'en', 'upload_tmp_dir is enabled, which is the recommended setting.');`
