### ISSUE TITLE
Prompt users to enable TLS

### ISSUE THREAD

**Issue by strugee** [matomo-org/plugin-SecurityInfo#4]
SecurityInfo should prompt the user to turn on SSL/TLS redirection. Note that doing this at the webserver level is not enough because then cookies don't get the "secure" flag.

**Comment by rugk** [comment]
:+1:

**Comment by mattab** [comment]
Thanks for the suggestion, that's a great & simple idea

**Comment by Findus23** [comment]
This has been added with https://github.com/matomo-org/matomo/pull/13193 a long time ago
