### ISSUE TITLE
Something is wrong with upload_tmp_dir security test

### ISSUE THREAD

**Issue by crankedguy** [matomo-org/plugin-SecurityInfo#44]
Hi,
something is wrong with your upload_tmp_dir security test
This is an excerpt of phpinfo() on my matomo instance

upload_tmp_dir | /home/xxx/tmp_php | /home/xxx/tmp_php

and this is the directory to it : 

drwx------  2 xxx xxx 4096 Sep 26 19:33 tmp_php

When running the test I always get
"upload_tmp_dir is disabled, or is set to a common world-writable directory. This typically allows other users on this server to access temporary copies of files uploaded via your PHP scripts. You should set upload_tmp_dir to a non-world-readable directory"

**Comment by tsteur** [comment]
This might be actually an issue in the `PhpSecInfo` library. There were some improvements made eg in https://github.com/matomo-org/plugin-SecurityInfo/pull/20 but maybe that patch isn't covering everything or so.

**Comment by Findus23** [comment]
@tsteur It is quite likely that this issue was fixed by #20 as it is older (I just moved it over a few days ago).

@crankedguy If you or someone else can reproduce this issue in the latest version of the plugin, can you please reopen this issue or create a new one.
